@'
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url><loc>https://toolhub-fresh.vercel.app/</loc><lastmod>2026-06-20</lastmod><priority>1.0</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/ai-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/image-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/pdf-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/dev-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/text-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/business-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/utility-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/education-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/design-tools</loc><lastmod>2026-06-20</lastmod><priority>0.9</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/image-to-jpg</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/image-to-png</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/image-to-webp</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/image-compressor</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/image-resizer</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/pdf-to-word</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/pdf-merger</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/pdf-splitter</loc><lastmod>2026-06-20</lastmod><priority>0.8</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/prompt-generator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/yt-title</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/yt-description</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/blog-outline</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/hashtag-generator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/caption-generator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/hook-generator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/tts</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/json-formatter</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/json-validator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/base64-encoder</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/base64-decoder</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/uuid-generator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/jwt-decoder</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/regex-tester</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/password-generator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/sql-formatter</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/xml-formatter</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/html-formatter</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/css-minifier</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/js-minifier</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/hash-generator</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/lorem-ipsum</loc><lastmod>2026-06-20</lastmod><priority>0.7</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/word-counter</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/text-case</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/remove-duplicates</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/markdown-editor</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/diff-checker</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/qr-generator</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/invoice-generator</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/resume-builder</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/business-name</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/password-strength</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/unit-converter</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/currency-converter</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/timezone-converter</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/color-picker</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/gradient-generator</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/palette-extractor</loc><lastmod>2026-06-20</lastmod><priority>0.6</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/age-calculator</loc><lastmod>2026-06-20</lastmod><priority>0.5</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/bmi-calculator</loc><lastmod>2026-06-20</lastmod><priority>0.5</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/percentage-calculator</loc><lastmod>2026-06-20</lastmod><priority>0.5</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/loan-calculator</loc><lastmod>2026-06-20</lastmod><priority>0.5</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/about</loc><lastmod>2026-06-20</lastmod><priority>0.4</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/contact</loc><lastmod>2026-06-20</lastmod><priority>0.4</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/privacy</loc><lastmod>2026-06-20</lastmod><priority>0.3</priority></url>
<url><loc>https://toolhub-fresh.vercel.app/terms</loc><lastmod>2026-06-20</lastmod><priority>0.3</priority></url>
</urlset>
'@ | Set-Content -Path public\sitemap.xml -Encoding UTF8